---
title: "LBB DV"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: 
      bg: white
      fg: darkblue
    
---

```{r setup, include=FALSE}

# GOALS:
# - (1 Point) Tahapan data pre-processing menggunakan dplyr
# - (1 Point) Plot yang ditampilkan pada dashboard sudah interaktif
# - (1 Point) Setiap plot yang ditampilkan menampilkan informasi yang relevan dari dashboard

library(flexdashboard)

#Meload library


library(shiny)
library(shinydashboard)
library(tidyverse)
library(plotly)
library(scales)
library(glue)
library(DT)
library(wordcloud2)
library(readr)
library(dplyr)
```

```{r}
#membaca data

spotify <- read_csv("data.csv")

#dplyr
spotify_clean <- 
  spotify %>% 
  mutate(
    explicit = as.factor(explicit),
    mode = as.factor(mode),
    year = as.numeric(year),
    acousticness = as.numeric(acousticness),
    danceability = as.numeric(danceability),
    energy = as.numeric(energy),
    instrumentalness = as.numeric(instrumentalness),
    liveness = as.numeric(liveness),
    speechiness = as.numeric(speechiness),
    loudness = as.numeric(loudness),
    valence = as.numeric(valence)
  
  )
```

Column {data-width=600}
-----------------------------------------------------------------------
### Top Songs in 2020
```{r}


   data_agg2 <- spotify_clean %>% 
      filter(year == 2020) %>% 
      select(name, popularity, artists) %>% 
      arrange(desc(popularity)) %>% 
      mutate(text = glue("popularity: {popularity}
                          artists: {artists}")) %>% 
      head(10)

    plot_rank <- ggplot(data_agg2, 
                        aes(x = popularity, y = reorder(name, popularity), 
                            text = text)) +
      geom_col(aes(fill = popularity)) +
      scale_y_discrete(labels = wrap_format(30)) + 
      scale_x_continuous(limits = c(0, 100), breaks = seq(0, 100, 10)) +
      scale_fill_gradient(low = "cyan", high = "darkblue") + 
      labs(x = "Popularity (0-100)", y = NULL, 
           title = glue("Top Most Popular Songs 2020")) +
      theme_minimal()
    
    ggplotly(plot_rank, tooltip = "text")

```   


Column {data-width=400}
-----------------------------------------------------------------------

### Music Taste Preference on Spotify

```{r}
#aggregasi data
spotify_by_year <- spotify_clean %>% 
                   group_by(year) %>%
                  summarise(across(c(-artists, -duration_ms, -explicit, -mode, -name, -release_date, -tempo, -id, -loudness, -popularity), mean, na.rm = TRUE))

#plot
# your code here
    data_agg1 <- spotify_by_year %>% 
      select(-key) %>% 
      gather(key = "Variable", value = "Value", - year)
    
    plot1<- ggplot(data_agg1, aes(x = year, y = Value)) + 
      geom_line(aes(color = Variable))  + 
      guides(scale = "none") + 
      labs(x = "Year", y = "Value", title = "Preference Music in the Past Century") + 
      scale_x_continuous(limits = c(1921, 2020), breaks = seq(1921, 2020, 20)) +
      theme_minimal()
    
    ggplotly(plot1)
```    
    
### Top Genres by Popularity

```{r}
spotify2 <- read_csv("top10s.csv")
spotify2_clean <- 
  spotify2 %>% 
  mutate(
    genre = as.factor(genre),
    year = as.numeric(year),)


spotify_by_genre <- spotify2_clean %>% 
                   group_by(genre) %>%
                  summarise(mean_popularity = mean(popularity)) %>% 
  ungroup()
spotify_by_genre$mean_popularity <-round(spotify_by_genre$mean_popularity, digits=2)

wordcloud2(data= spotify_by_genre, color = "random-dark", size=0.3, backgroundColor = "transparent")


```





